// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQBiPHCVrE-X_K7skPbJ-mEHldr0JkTE',
    appId: '1:14882046770:web:16cfd2814bea8ef1bf4d2b',
    messagingSenderId: '14882046770',
    projectId: 'fir-demo-22765',
    authDomain: 'fir-demo-22765.firebaseapp.com',
    storageBucket: 'fir-demo-22765.appspot.com',
    measurementId: 'G-5HMZXKCP1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQFs3220VptYlKUV_IeAPY9xu3H1Lnxok',
    appId: '1:14882046770:android:1442f8a70f313027bf4d2b',
    messagingSenderId: '14882046770',
    projectId: 'fir-demo-22765',
    storageBucket: 'fir-demo-22765.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQBiPHCVrE-X_K7skPbJ-mEHldr0JkTE',
    appId: '1:14882046770:web:49271b08960f1c8fbf4d2b',
    messagingSenderId: '14882046770',
    projectId: 'fir-demo-22765',
    authDomain: 'fir-demo-22765.firebaseapp.com',
    storageBucket: 'fir-demo-22765.appspot.com',
    measurementId: 'G-2F7HCZJDKE',
  );
}
